export const FEATURE_KEYWORDS: Record<string, string[]> = {
  authentication: [
    'logowanie',
    'login',
    'rejestracja',
    'konto',
    'użytkownik',
    'profil',
    'hasło',
    'autoryzacja',
    'member',
    'user',
  ],
  'push-notifications': [
    'powiadomienia',
    'notyfikacje',
    'alert',
    'przypomnienie',
    'notification',
    'push',
  ],
  payments: [
    'płatność',
    'płatności',
    'platnosc',
    'platnosci',
    'karta',
    'przelew',
    'blik',
    'zakup',
    'sklep',
    'sprzedaż',
    'koszyk',
    'checkout',
    'payment',
    'e-commerce',
    'zamówienie',
    'zamowienie',
    'zamówić',
    'zamowic',
    'zamawiać',
    'zamawiac',
    'zamwaic',
    'jedzenie',
    'restauracja',
    'dania',
  ],
  maps: [
    'mapa',
    'lokalizacja',
    'gps',
    'nawigacja',
    'location',
    'trasa',
    'miejsce',
    'adres',
    'dostawa',
    'kierowca',
  ],
  camera: [
    'zdjęcie',
    'foto',
    'kamera',
    'skan',
    'qr',
    'galeria',
    'image',
    'photo',
    'upload',
  ],
  chat: [
    'czat',
    'wiadomość',
    'komunikator',
    'chat',
    'message',
    'rozmowa',
    'kontakt',
    'support',
    'obsługa',
  ],
  'social-media': [
    'social',
    'facebook',
    'instagram',
    'udostępnianie',
    'share',
    'like',
    'follow',
    'komentarz',
  ],
  analytics: [
    'statystyki',
    'analityka',
    'raport',
    'dashboard',
    'wykres',
    'dane',
    'analytics',
    'tracking',
  ],
  'admin-panel': [
    'admin',
    'panel',
    'zarządzanie',
    'cms',
    'backend',
    'moderacja',
    'kontrola',
  ],
  multilanguage: [
    'język',
    'tłumaczenie',
    'polski',
    'angielski',
    'międzynarodowy',
    'language',
    'multi',
  ],
  'dark-mode': ['ciemny', 'dark', 'tryb', 'theme', 'motyw'],
};

export const ALLOWED_FEATURES = Object.keys(FEATURE_KEYWORDS);
